# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5212ca08b1ba5f3ed7559971ee623284d39dcf4156aa662b0e5f9a9682794093a19ba116e364ca4eadbe40019f320645649e8fa61fa9b460d95720db228d3cce

test:
  secret_key_base: 354fa37774f2faaa25ca9ac49018f932892ab42450d2b86974fe1ff3d08deb714e22ea1f42dd059a4fa85674c6e6a584952c13854c38f923ad4080aac4d44f41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
